# npm install --save-dev eslint-config-standard eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node babel-eslint
extends: 'standard'
#Suporte a stage 3 (remover quando entrar no javascript)
parser: 'babel-eslint'
