---
# Configuração do Servidor HTTP Express
# body-parser: https://github.com/expressjs/body-parser

# TODO: Não deixe um grupo vazio se não irá substituir tudo

logger:
  blessed:
    enabled: false
  console:
    enabled: false
    handleExceptions: true

# Ativa modo ncurses (Carrega interface ncurse para monitorar aplicação visualmente)
blessed:
  enabled: false

